// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/kvstore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArgs) Reset() {
	*x = GetArgs{}
	mi := &file_proto_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArgs) ProtoMessage() {}

func (x *GetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArgs.ProtoReflect.Descriptor instead.
func (*GetArgs) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *GetArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	// If I am not the leader, tell the client who is
	LeaderHint    string `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_proto_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *GetReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetReply) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type PutArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Essential for "Exactly-Once" execution
	ClientId      string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     int64  `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutArgs) Reset() {
	*x = PutArgs{}
	mi := &file_proto_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutArgs) ProtoMessage() {}

func (x *PutArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutArgs.ProtoReflect.Descriptor instead.
func (*PutArgs) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *PutArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutArgs) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PutArgs) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type PutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutReply) Reset() {
	*x = PutReply{}
	mi := &file_proto_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutReply) ProtoMessage() {}

func (x *PutReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutReply.ProtoReflect.Descriptor instead.
func (*PutReply) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *PutReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutReply) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

type DeleteArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArgs) Reset() {
	*x = DeleteArgs{}
	mi := &file_proto_kvstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArgs) ProtoMessage() {}

func (x *DeleteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArgs.ProtoReflect.Descriptor instead.
func (*DeleteArgs) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteArgs) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DeleteArgs) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type DeleteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LeaderHint    string                 `protobuf:"bytes,2,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReply) Reset() {
	*x = DeleteReply{}
	mi := &file_proto_kvstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReply) ProtoMessage() {}

func (x *DeleteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReply.ProtoReflect.Descriptor instead.
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteReply) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

// --- Paxos Phase 1 ---
type PrepareArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Proposal Number (must be strictly increasing)
	ProposalNumber int64 `protobuf:"varint,1,opt,name=proposal_number,json=proposalNumber,proto3" json:"proposal_number,omitempty"`
	// Multi-Paxos: We run many instances of Paxos.
	// seq=1 is the first log entry, seq=2 is the second...
	Seq           int64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareArgs) Reset() {
	*x = PrepareArgs{}
	mi := &file_proto_kvstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareArgs) ProtoMessage() {}

func (x *PrepareArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareArgs.ProtoReflect.Descriptor instead.
func (*PrepareArgs) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{6}
}

func (x *PrepareArgs) GetProposalNumber() int64 {
	if x != nil {
		return x.ProposalNumber
	}
	return 0
}

func (x *PrepareArgs) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PrepareReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Acceptor returns the highest proposal number it has promised
	HighestProposal int64 `protobuf:"varint,1,opt,name=highest_proposal,json=highestProposal,proto3" json:"highest_proposal,omitempty"`
	Success         bool  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Optimisation: If I already accepted something for this seq,
	// I tell you so you can adopt it (forcing consensus).
	ValAlreadyAccepted string `protobuf:"bytes,3,opt,name=val_already_accepted,json=valAlreadyAccepted,proto3" json:"val_already_accepted,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrepareReply) Reset() {
	*x = PrepareReply{}
	mi := &file_proto_kvstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareReply) ProtoMessage() {}

func (x *PrepareReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareReply.ProtoReflect.Descriptor instead.
func (*PrepareReply) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{7}
}

func (x *PrepareReply) GetHighestProposal() int64 {
	if x != nil {
		return x.HighestProposal
	}
	return 0
}

func (x *PrepareReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PrepareReply) GetValAlreadyAccepted() string {
	if x != nil {
		return x.ValAlreadyAccepted
	}
	return ""
}

// --- Paxos Phase 2 ---
type AcceptArgs struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProposalNumber int64                  `protobuf:"varint,1,opt,name=proposal_number,json=proposalNumber,proto3" json:"proposal_number,omitempty"`
	Seq            int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Value          string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // The actual command (e.g., "PUT:x:5")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptArgs) Reset() {
	*x = AcceptArgs{}
	mi := &file_proto_kvstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptArgs) ProtoMessage() {}

func (x *AcceptArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptArgs.ProtoReflect.Descriptor instead.
func (*AcceptArgs) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptArgs) GetProposalNumber() int64 {
	if x != nil {
		return x.ProposalNumber
	}
	return 0
}

func (x *AcceptArgs) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AcceptArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AcceptReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HighestProposal int64                  `protobuf:"varint,1,opt,name=highest_proposal,json=highestProposal,proto3" json:"highest_proposal,omitempty"` // If I reject, I tell you why (I saw a higher N)
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcceptReply) Reset() {
	*x = AcceptReply{}
	mi := &file_proto_kvstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptReply) ProtoMessage() {}

func (x *AcceptReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptReply.ProtoReflect.Descriptor instead.
func (*AcceptReply) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{9}
}

func (x *AcceptReply) GetHighestProposal() int64 {
	if x != nil {
		return x.HighestProposal
	}
	return 0
}

func (x *AcceptReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- Paxos Phase 3 (Commit) ---
type DecidedArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecidedArgs) Reset() {
	*x = DecidedArgs{}
	mi := &file_proto_kvstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecidedArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecidedArgs) ProtoMessage() {}

func (x *DecidedArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecidedArgs.ProtoReflect.Descriptor instead.
func (*DecidedArgs) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{10}
}

func (x *DecidedArgs) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DecidedArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DecidedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecidedReply) Reset() {
	*x = DecidedReply{}
	mi := &file_proto_kvstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecidedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecidedReply) ProtoMessage() {}

func (x *DecidedReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecidedReply.ProtoReflect.Descriptor instead.
func (*DecidedReply) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{11}
}

func (x *DecidedReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CatchUpArgs struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LocalCommitIndex int64                  `protobuf:"varint,1,opt,name=local_commit_index,json=localCommitIndex,proto3" json:"local_commit_index,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CatchUpArgs) Reset() {
	*x = CatchUpArgs{}
	mi := &file_proto_kvstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchUpArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchUpArgs) ProtoMessage() {}

func (x *CatchUpArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchUpArgs.ProtoReflect.Descriptor instead.
func (*CatchUpArgs) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{12}
}

func (x *CatchUpArgs) GetLocalCommitIndex() int64 {
	if x != nil {
		return x.LocalCommitIndex
	}
	return 0
}

type CatchUpReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// We send a map of Sequence Number -> Command
	MissingEntries map[int64]string `protobuf:"bytes,1,rep,name=missing_entries,json=missingEntries,proto3" json:"missing_entries,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CatchUpReply) Reset() {
	*x = CatchUpReply{}
	mi := &file_proto_kvstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchUpReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchUpReply) ProtoMessage() {}

func (x *CatchUpReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchUpReply.ProtoReflect.Descriptor instead.
func (*CatchUpReply) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{13}
}

func (x *CatchUpReply) GetMissingEntries() map[int64]string {
	if x != nil {
		return x.MissingEntries
	}
	return nil
}

var File_proto_kvstore_proto protoreflect.FileDescriptor

const file_proto_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x13proto/kvstore.proto\x12\akvstore\"\x1b\n" +
	"\aGetArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"W\n" +
	"\bGetReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\"m\n" +
	"\aPutArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x03R\trequestId\"E\n" +
	"\bPutReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\tR\n" +
	"leaderHint\"Z\n" +
	"\n" +
	"DeleteArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x03R\trequestId\"H\n" +
	"\vDeleteReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vleader_hint\x18\x02 \x01(\tR\n" +
	"leaderHint\"H\n" +
	"\vPrepareArgs\x12'\n" +
	"\x0fproposal_number\x18\x01 \x01(\x03R\x0eproposalNumber\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\"\x85\x01\n" +
	"\fPrepareReply\x12)\n" +
	"\x10highest_proposal\x18\x01 \x01(\x03R\x0fhighestProposal\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x120\n" +
	"\x14val_already_accepted\x18\x03 \x01(\tR\x12valAlreadyAccepted\"]\n" +
	"\n" +
	"AcceptArgs\x12'\n" +
	"\x0fproposal_number\x18\x01 \x01(\x03R\x0eproposalNumber\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"R\n" +
	"\vAcceptReply\x12)\n" +
	"\x10highest_proposal\x18\x01 \x01(\x03R\x0fhighestProposal\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"5\n" +
	"\vDecidedArgs\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"(\n" +
	"\fDecidedReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\vCatchUpArgs\x12,\n" +
	"\x12local_commit_index\x18\x01 \x01(\x03R\x10localCommitIndex\"\xa5\x01\n" +
	"\fCatchUpReply\x12R\n" +
	"\x0fmissing_entries\x18\x01 \x03(\v2).kvstore.CatchUpReply.MissingEntriesEntryR\x0emissingEntries\x1aA\n" +
	"\x13MissingEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xf3\x02\n" +
	"\aKVStore\x12*\n" +
	"\x03Get\x12\x10.kvstore.GetArgs\x1a\x11.kvstore.GetReply\x12*\n" +
	"\x03Put\x12\x10.kvstore.PutArgs\x1a\x11.kvstore.PutReply\x123\n" +
	"\x06Delete\x12\x13.kvstore.DeleteArgs\x1a\x14.kvstore.DeleteReply\x126\n" +
	"\aPrepare\x12\x14.kvstore.PrepareArgs\x1a\x15.kvstore.PrepareReply\x123\n" +
	"\x06Accept\x12\x13.kvstore.AcceptArgs\x1a\x14.kvstore.AcceptReply\x126\n" +
	"\aDecided\x12\x14.kvstore.DecidedArgs\x1a\x15.kvstore.DecidedReply\x126\n" +
	"\aCatchUp\x12\x14.kvstore.CatchUpArgs\x1a\x15.kvstore.CatchUpReplyB1Z/github.com/yashp1402/distributed-kv-store/protob\x06proto3"

var (
	file_proto_kvstore_proto_rawDescOnce sync.Once
	file_proto_kvstore_proto_rawDescData []byte
)

func file_proto_kvstore_proto_rawDescGZIP() []byte {
	file_proto_kvstore_proto_rawDescOnce.Do(func() {
		file_proto_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kvstore_proto_rawDesc), len(file_proto_kvstore_proto_rawDesc)))
	})
	return file_proto_kvstore_proto_rawDescData
}

var file_proto_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_kvstore_proto_goTypes = []any{
	(*GetArgs)(nil),      // 0: kvstore.GetArgs
	(*GetReply)(nil),     // 1: kvstore.GetReply
	(*PutArgs)(nil),      // 2: kvstore.PutArgs
	(*PutReply)(nil),     // 3: kvstore.PutReply
	(*DeleteArgs)(nil),   // 4: kvstore.DeleteArgs
	(*DeleteReply)(nil),  // 5: kvstore.DeleteReply
	(*PrepareArgs)(nil),  // 6: kvstore.PrepareArgs
	(*PrepareReply)(nil), // 7: kvstore.PrepareReply
	(*AcceptArgs)(nil),   // 8: kvstore.AcceptArgs
	(*AcceptReply)(nil),  // 9: kvstore.AcceptReply
	(*DecidedArgs)(nil),  // 10: kvstore.DecidedArgs
	(*DecidedReply)(nil), // 11: kvstore.DecidedReply
	(*CatchUpArgs)(nil),  // 12: kvstore.CatchUpArgs
	(*CatchUpReply)(nil), // 13: kvstore.CatchUpReply
	nil,                  // 14: kvstore.CatchUpReply.MissingEntriesEntry
}
var file_proto_kvstore_proto_depIdxs = []int32{
	14, // 0: kvstore.CatchUpReply.missing_entries:type_name -> kvstore.CatchUpReply.MissingEntriesEntry
	0,  // 1: kvstore.KVStore.Get:input_type -> kvstore.GetArgs
	2,  // 2: kvstore.KVStore.Put:input_type -> kvstore.PutArgs
	4,  // 3: kvstore.KVStore.Delete:input_type -> kvstore.DeleteArgs
	6,  // 4: kvstore.KVStore.Prepare:input_type -> kvstore.PrepareArgs
	8,  // 5: kvstore.KVStore.Accept:input_type -> kvstore.AcceptArgs
	10, // 6: kvstore.KVStore.Decided:input_type -> kvstore.DecidedArgs
	12, // 7: kvstore.KVStore.CatchUp:input_type -> kvstore.CatchUpArgs
	1,  // 8: kvstore.KVStore.Get:output_type -> kvstore.GetReply
	3,  // 9: kvstore.KVStore.Put:output_type -> kvstore.PutReply
	5,  // 10: kvstore.KVStore.Delete:output_type -> kvstore.DeleteReply
	7,  // 11: kvstore.KVStore.Prepare:output_type -> kvstore.PrepareReply
	9,  // 12: kvstore.KVStore.Accept:output_type -> kvstore.AcceptReply
	11, // 13: kvstore.KVStore.Decided:output_type -> kvstore.DecidedReply
	13, // 14: kvstore.KVStore.CatchUp:output_type -> kvstore.CatchUpReply
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_kvstore_proto_init() }
func file_proto_kvstore_proto_init() {
	if File_proto_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kvstore_proto_rawDesc), len(file_proto_kvstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kvstore_proto_goTypes,
		DependencyIndexes: file_proto_kvstore_proto_depIdxs,
		MessageInfos:      file_proto_kvstore_proto_msgTypes,
	}.Build()
	File_proto_kvstore_proto = out.File
	file_proto_kvstore_proto_goTypes = nil
	file_proto_kvstore_proto_depIdxs = nil
}
